Added skip wallpaper flag
dylanaraps/wal pull request #23
Opened 2017-04-08 09:48 UTC by hallgat89

This is a flag to skip setting the wallpaper. Why? Wal sets every wallpaper in "filled" mode, even if I would like to use a tiled pattern instead. With this flag I disable the wallpaper, and set the background myself.

2017-04-09 10:37 UTC, dylanaraps requested changes

2017-04-09 10:37 UTC, dylanaraps commented on wal
> +    if [[ "$nowall" != "on" ]]
```sh
if [[ -z "$nowall" ]]; then
```

2017-04-09 10:37 UTC, dylanaraps commented on wal
> +        out "skipping wallpaper"
```sh
out "wallpaper: '-n' was used, skipping wallpaper"
```

2017-04-09 10:37 UTC, dylanaraps commented on wal
> +    while getopts ":a:chi:o:qrtn" opt; do
```sh
while getopts ":a:chi:no:qrt" opt; do
```

2017-04-09 10:37 UTC, dylanaraps commented on wal
> +            "n") nowall="on" ;;
Move this so that it's in alphabetical order with the other args.

2017-04-09 10:53 UTC, hallgat89 reviewed
It's okay for me :)

2017-04-09 10:55 UTC, dylanaraps commented
It may work fine but it's not yet up to my standards. The PR only needs a few changes before it matches the style of the rest of the script.

I won't merge this until the above changes are made.

2017-04-09 11:15 UTC, hallgat89 commented on wal
> +    if [[ "$nowall" != "on" ]]
done

2017-04-09 11:15 UTC, hallgat89 commented on wal
> +        out "skipping wallpaper"
done

2017-04-09 11:15 UTC, hallgat89 commented on wal
> +    while getopts ":a:chi:o:qrtn" opt; do
Done, and ordered

2017-04-09 11:15 UTC, hallgat89 commented on wal
> +            "n") nowall="on" ;;
done and ordered

2017-04-09 11:16 UTC, hallgat89 reviewed
updated

2017-04-09 12:43 UTC, dylanaraps reviewed
Once this is done, I'll merge.

Thanks for the PR! :)

2017-04-09 12:43 UTC, dylanaraps commented on wal
> +
Remove this blank line.

2017-04-09 12:43 UTC, dylanaraps commented on wal
> +
Remove this blank line.

2017-04-09 19:16 UTC, hallgat89 commented on wal
> +
done

2017-04-09 19:16 UTC, hallgat89 commented on wal
> +
done

2017-04-09 23:21 UTC, dylanaraps commented
LGTM :+1:

Thanks for the PR!

2017-04-09 23:21 UTC, dylanaraps approved these changes

2017-04-09 23:21 UTC, merged

2017-04-10 06:05 UTC, hallgat89 commented
Thanks for the cooperation :)